name: convert

on: push

jobs:
  UML_to_SVG:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Make tmp/ dir'
      run: |
        mkdir -p tmp/
        ls -la input/

    - name: 'Convert'
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: input
        message: "Rendered SVG files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Move *.svg to tmp/ dir'
      run: |
        mv input/*.svg tmp/
        ls -la input/
        ls -la tmp/

    - name: 'Upload'
      uses: actions/upload-artifact@v2
      with:
        path: tmp
        if-no-files-found: ignore
        retention-days: 1