name: convert

on: push

jobs:
  UML_to_SVG:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      run: |
        mkdir -p output/

    - name: 'Convert'
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: output
        message: "Rendered SVG files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Upload'
      uses: actions/upload-artifact@v2
      with:
        path: output
        if-no-files-found: ignore
        retention-days: 1