name: convert

on: push

jobs:
  GENERATE_SVG:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Convert'
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: example
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          path: example
          if-no-files-found: ignore
          retention-days: 3