name: convert

on:
    workflow_dispatch

jobs:
  UML_to_SVG:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Convert'
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: tmp
        message: "Add rendered SVG files to tmp/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Upload'
      uses: actions/upload-artifact@v2
      with:
        path: tmp
        if-no-files-found: ignore
        retention-days: 1