name: convert

on: push

jobs:
  UML_to_SVG:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Make tmp/ dir'
      run: |
        mkdir -p tmp/

    - name: 'Convert'
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: example
        message: "Rendered SVG files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Move *.svg files to tmp/ dir'
      run: |
        pwd
        ls -la
        ls -la example/
        mv example/yet_another_example.svg tmp/

    - name: 'Upload'
      uses: actions/upload-artifact@v2
      with:
        path: tmp
        if-no-files-found: ignore
        retention-days: 1