name: Generate PlantUML Diagrams

on: push
#   pull_request:
#     branches:
#       - 'main'

jobs:
  Generate_PlantUML:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 'Get changed UML files in repo'
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)"

      - name: 'Generate SVG Diagrams'
        #continue-on-error: true
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          path: input/*.svg
          if-no-files-found: ignore
          retention-days: 2
