name: Generate PlantUML Diagrams

on: push


jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)"

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{steps.getfile.outputs.files}}

      - name: 'Check'
        run: |
            pwd
            ls -la tmp/
            ls -la

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          path: tmp/*.svg
          if-no-files-found: ignore
          retention-days: 1