name: Generate PlantUML Diagrams

on: push


jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg tmp/*.puml

      - name: 'Check'
        run: |
            pwd
            ls -la tmp/
            ls -la

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          path: tmp/*.svg
          if-no-files-found: ignore
          retention-days: 1